using System.Diagnostics.CodeAnalysis;
using Microsoft.CodeAnalysis;

namespace Xamarin.Macios.Generator.Attributes;

public static class ModelParser
{

    public static bool TryParse(SyntaxNode attributeSyntax, AttributeData attributeData,
        [NotNullWhen(true)] out ModelData? data)
    {
        data = default;

        var count = attributeData.ConstructorArguments.Length;
        switch (count)
        {
            case 1: // could be auto-gen or just name..
                var attrDataArg = attributeData.NamedArguments[0].Key;
                if (attrDataArg == "AutoGeneratedName") {
                    data = new() { AutoGeneratedName = (bool)attributeData.ConstructorArguments[0].Value! };
                    return true;
                } else if (attrDataArg == "Name") {
                    data = new() { Name = (string)attributeData.ConstructorArguments[0].Value! };
                    return true;
                }
                return false;
            default: // default when 0 args?
                return false;
        }
    }
}
